---
- name: Setup environment to run the sample
  hosts: all
  remote_user: root
  become:      yes

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - geerlingguy.docker

  tasks:
    - debug:
        msg: task1

    - name: Include vars
      include_vars:
        dir: vars
        
    - name: Setup base config for docker
      import_tasks: setup.yml
      tags: base
    
    - name: Build the images for jenkins and sonar
      import_tasks: docker.yml

    - name: Add some Plugins to Jenkins
      import_tasks: jenkins.yml
